### PR TITLE
Adding New Iterator Transform: foreach

### PR DESCRIPTION
**Pull request by aertoria**
Adding New Iterator Transform: foreach
Syntax example:    
OLD:    `SUM(SCALE(-10d:M:cpu{device=*}:avg, -10d:M:count{device=*}:avg))`
NEW:   `SUM(foreach(-10d:M:cpu{device=*}:avg,-10d:M:count{device=*}:avg,$device,$SCALE))`

Scope: Can apply on any existing TRANSFORM with their existing constants requirement if any.

Detail:
foreach is implemented against a new type "TRANSFORMITERATOR", which extends current type "TRANSFORM". This architecture allows "foreach" being treated same way in metricReader and factory. However, they are different in that:

CURRENT TYPE Transform.transform:   `taking Array<Metric>, giving Array<Metric>`
NEW TYPE TransformIterator.iterate: ` taking Array<Metric>, giving Array<TransformExecutable>`    

in above, each TransformExecutable is `Array<Metric>`, so they that can be consumed directly by any Transform.transform

### CODE REVIEW

**Comment by aertoria** [comment]
@saaja-sfdc 
Let me know your thought. Thanks.

**Comment by aertoria** [comment]
@saaja-sfdc @bsura 
Update. Below is a dashboard that illustrates the usage of transform 'foreach'. It is right now running at DBClouds' private Argus and it becomes one of those very popular transforms since the release months back. Hope it's helpful.

after login
`http://adhoc-db1-1-crd.eng.sfdc.net:8020/app/#/dashboards/308501`

usage:
`SUM(1464803454:1466045054:p90_sandbox:podperc90{podId=*}:avg,1464803454:1466045054:p90_sandbox:podperc90{podId=*}:avg)`
versus
`foreach(1464803454:1466045054:p90_sandbox:podperc90{podId=*}:avg,1464803454:1466045054:p90_sandbox:podperc90{podId=*}:avg,$podId,$SUM)`

You may keep chaining other transform with any constants after that. Let me know if it helps.

**Comment by bsura** [comment]
@aertoria Can we close this pull request? We already have a GroupBy Transform that should be able to achieve this. Also if we are adding this Transform, then it should probably be done the way we had discussed it the other day.

**Comment by aertoria** [comment]
As we discussed the other one will be ready for you to pull in about 1 week. But before that if you have something ready to ship then just close this one. Thanks

**Comment by bsura** [comment]
Check out this PR which has already been submitted. 
https://github.com/SalesforceEng/Argus/pull/152

**Comment by bsura** [comment]
Closing this one.

**Comment by aertoria** [comment]
Thanks

**Comment by aertoria** [comment]
@cksassy

**Pull request closed without merging**
