### PR TITLE
Add new DVA services status dashboard

### PR DESCRIPTION
**Pull request by cnardi-dev**
Updates to all markup for building a DVA services status dashboard.

### CODE REVIEW

**Comment by cnardi-dev** [comment]
Not sure why I can't remove the commits prior to today, unless they haven't been merged yet.  Only commits from today, June 30th should be included for this PR.  Previous commit are included in separate PR.

**Comment by saaja-sfdc** [comment]
You should be able to rebase your branch.  They have been merged.  But for this PR it's fine.  I'll verify it locally and then if all's good, we'll push it to dev.

**Comment by cnardi-dev** [comment]
This PR also includes the setup for the loading spinner on charts, except small charts like the DVA Services Status Dashboards.

**Comment by saaja-sfdc** [comment]
Hi @cnardi-dev This looks great, there's only one small issue where having a space in the value of ag-indicator's 'name' attribute breaks the rendering of the indicator bubble.  I'll file a separate issue for that.

**Pull request merged**
