### PR TITLE
add feature for handing the operations when two data points do not share common time stamp

### PR DESCRIPTION
**Pull request by aertoria**
Changing from 'full' to 'union' as optional constant

### CODE REVIEW

**Comment by saaja-sfdc** [comment]
@aertoria Can you please rebase so I can merge.  Before I actually merge it, I'll request that you update the [wiki](https://github.com/SalesforceEng/Argus/wiki/Transforms) with the info for the new parameter.  Once the documentation is updated, I'll go ahead and merge the change.

Just something to the effect that by default, it does an intersection across timestamps and that you can specify a union with the parameter.  It does need to be reflected in the wiki for any affected transform.

Thanks for contributing!

**Comment by aertoria** [comment]
@saaja-sfdc  Thanks for working on this.
1.Let me know if you are able to merge now, or you still want me to do a REBASE.
2.What's the best practice of contributing content on wiki?  I have wiki clone locally and updated, But I don't have permission to directly write back. Plz advise

**Comment by saaja-sfdc** [comment]
Hi @aertoria , yep we are working on getting contribution guidelines in place.  For wiki changes, you should fork the wiki and then open an issue as described in this process.

https://gist.github.com/larrybotha/10650410

**Comment by aertoria** [comment]
@saaja-sfdc 
Thanks Tom! 
Let me know when you done this pr. some other stuff in my other branches will follow.

**Pull request merged**
